### ISSUE TITLE
Handling hitpoints

### ISSUE THREAD

**Issue by geddingj** [OSU-CS361-W17/group16_project3#7]
How did we want a ships health dealt with? 

I know we discussed having a new variable to keep track of it but I don't recall coming to a conclusion about it.

**Comment by jiayuhan94** [comment]
So based on what I remembered, it should be a "health" variable and a
"hit", could be called whatever you prefer, to check if a ship is sank or
not. military ships` health are the same as their length, but the civilian
ships` are different.
Also, I got why the not firing same spot not working. it  was because the
'contain' function which java has doesnt work properly, so I have to write
our own contain function to make it work. I will see if I could get that
fixed before meeting.

**Comment by geddingj** [comment]
hit points made as a 'health' variable

**Comment by jiayuhan94** [comment]
changed the game winning condition based on the new ship model we have,
need some one to check it and accept it.
